# Generated by Django 4.1.4 on 2023-01-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_remove_livro_data_publicacao_livro_ano_publicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='livro/livro/'),
        ),
    ]
